apiVersion: apps/v1 #  for k8s versions before 1.9.0 use apps/v1beta2  and before 1.8.0 use extensions/v1beta1
kind: Deployment
metadata:
  name: frontend
spec:
  selector:
    matchLabels:
      app: guestbook
      tier: frontend
  replicas: 1
  template:
    metadata:
      labels:
        app: guestbook
        tier: frontend
    spec:
      containers:
<<<<<<< HEAD
      - name: frontend
        image: docker.io/patrocinio/gb-frontend-amd64:backend
=======
      - name: php-redis
#        image: gcr.io/google_samples/gb-frontend:v5
        image: docker.io/patrocinio/gb-frontend-amd64:v9
>>>>>>> 3de525a98eda4a24fc0e906a853ca3f58f0e306f
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        env:
        - name: GET_HOSTS_FROM
          value: dns
          # If your cluster config does not include a dns service, then to
          # instead access environment variables to find service host
          # info, comment out the 'value: dns' line above, and uncomment the
          # line below:
          # value: env
        ports:
        - containerPort: 80
